config_partial.export_partial:
  path: '/admin/config/development/configuration/single/config-partial-export'
  defaults:
    _form: '\Drupal\config_partial_export\Form\ConfigPartialExportForm'
    _title: 'Partial Export'
  requirements:
    _permission: 'export configuration'

config_partial.export_partial_download:
  path: '/admin/config/development/configuration/single/partial-export-download'
  defaults:
    _controller: 'Drupal\config_partial_export\Controller\ConfigPartialExportController::downloadExport'
  requirements:
    _permission: 'export configuration'
